#!/usr/bin/env bash
# section-config.sh -- sourced by run-tests.sh; do not run standalone.
# Contract: the runner already defines set -uo pipefail and has sourced
# _lib.sh (check/check_rc/check_absent/lifecycle_start/_rand_port) and set
# HERE/PLUGIN/FIX/fails/flaky before sourcing this file. This file assumes
# those are already in scope.
declare -F check >/dev/null 2>&1 || { echo "section files are sourced by run-tests.sh; run: bash plugins/spec-workflow/tests/run-tests.sh" >&2; exit 2; }
echo "== config.py (shared loader) =="
CT="$(mktemp -d)"; mkdir -p "$CT/.claude"
cp "$FIX/valid.project.yaml" "$CT/.claude/project.yaml"
check "yaml dot-path get" "fixture-project" "$(python3 "$PLUGIN/scripts/config.py" "$CT" get project.name)"
check "yaml nested get" "true" "$(python3 "$PLUGIN/scripts/config.py" "$CT" get commands.gate)"
check "path verb resolves yaml" "project.yaml" "$(python3 "$PLUGIN/scripts/config.py" "$CT" path)"
check "json verb emits normalized" '"schemaVersion"' "$(python3 "$PLUGIN/scripts/config.py" "$CT" json)"
check "v2 dev array models get" "claude-haiku-4-5" "$(python3 "$PLUGIN/scripts/config.py" "$CT" get delegation.identities.dev.1.models.1)"
cp "$FIX/valid.project.json" "$CT/.claude/project.json"
check "yaml preferred over json" "project.yaml" "$(python3 "$PLUGIN/scripts/config.py" "$CT" path)"
rm -rf "$CT"
CJ="$(mktemp -d)"; mkdir -p "$CJ/.claude"
cp "$FIX/valid.project.json" "$CJ/.claude/project.json"
check "legacy json deprecation warning" "DEPRECATION" "$(python3 "$PLUGIN/scripts/config.py" "$CJ" json 2>&1 >/dev/null)"
check "legacy path resolves json" "project.json" "$(python3 "$PLUGIN/scripts/config.py" "$CJ" path 2>/dev/null)"
check "legacy devModel -> dev.models[0]" "sonnet" "$(python3 "$PLUGIN/scripts/config.py" "$CJ" get delegation.identities.dev.models.0 2>/dev/null)"
check "legacy reviewModel -> reviewer.models[0]" "sonnet" "$(python3 "$PLUGIN/scripts/config.py" "$CJ" get delegation.identities.reviewer.models.0 2>/dev/null)"
check "PROJECT_CONFIG override" "fixture-project" "$(PROJECT_CONFIG="$FIX/valid.project.yaml" python3 "$PLUGIN/scripts/config.py" "$CJ" get project.name)"
rm -rf "$CJ"

echo "== validate-config =="
out="$(python3 "$PLUGIN/scripts/validate-config.py" "$FIX/valid.project.yaml")"
check "valid yaml passes" "VALID: " "$out"
out="$(python3 "$PLUGIN/scripts/validate-config.py" "$FIX/broken.project.yaml" || true)"
check "broken yaml: schemaVersion 2" "schemaVersion must be 2" "$out"
check "broken yaml: statusFlow option" "'Done' has no matching status option id" "$out"
check "broken yaml: empty priority options" "priority.options is empty" "$out"
check "broken yaml: unknown board ref" "does not match any boards[].id" "$out"
check "broken yaml: unknown blockedBy epic" "unknown epic 'EZ'" "$out"
check "broken yaml: maxInProgress <= 0 rejected" "methodology.maxInProgress: must be >= 1 (got -3)" "$out"
check "broken yaml: graduationThreshold non-integer rejected" "methodology.graduationThreshold: must be an integer >= 1 (got 'many')" "$out"
out="$(python3 "$PLUGIN/scripts/validate-config.py" "$FIX/shorthand.project.yaml" || true)"
check "v2 shorthand dev model rejected" "'sonnet'" "$out"
check "v2 shorthand reviewer model rejected" "'opus'" "$out"
check "shorthand error names full nomenclature" "full model-id" "$out"
out="$(python3 "$PLUGIN/scripts/validate-config.py" "$FIX/valid.project.json")"
check "legacy json still VALID" "VALID: " "$out"
check "legacy json deprecation noted" "legacy" "$out"
check "legacy json shorthand allowed (devModel=sonnet)" "VALID: " "$out"
out="$(python3 "$PLUGIN/scripts/validate-config.py" "$FIX/broken.project.json" || true)"
check "broken: schemaVersion" "schemaVersion must be 1" "$out"
check "broken: statusFlow option" "'Done' has no matching status option id" "$out"
check "broken: empty priority options" "priority.options is empty" "$out"
check "broken: bad taskPrefix" "must be alphanumeric starting with a letter" "$out"
check "broken: unknown board ref" "does not match any boards[].id" "$out"
check "broken: overlapping ranges" "overlaps epic" "$out"
check "broken: unknown blockedBy epic" "unknown epic 'EZ'" "$out"
check "broken: bad untilStatus" "not in statusFlow" "$out"
check "broken: missing gate" "missing required key 'gate'" "$out"
check "broken: maxInProgress non-integer rejected" "methodology.maxInProgress: must be an integer >= 1 (got 'two')" "$out"
check "broken: graduationThreshold <= 0 rejected" "methodology.graduationThreshold: must be >= 1 (got 0)" "$out"
out="$(python3 "$PLUGIN/scripts/validate-config.py" "$FIX/bounds-bool.project.yaml" || true)"
check "maxInProgress bool rejected (not a valid integer)" "methodology.maxInProgress: must be an integer >= 1 (got True)" "$out"
out="$(python3 "$PLUGIN/scripts/validate-config.py" "$FIX/bounds-float.project.yaml" || true)"
check "graduationThreshold float rejected (not a valid integer)" "methodology.graduationThreshold: must be an integer >= 1 (got 3.0)" "$out"
out="$(python3 "$PLUGIN/scripts/validate-config.py" "$PLUGIN/templates/project.example.yaml" || true)"
check "template rejected (placeholders)" "template placeholder" "$out"

